### ISSUE TITLE
Deploying appliance with Portal Role should not require proxy_p12s.content

### ISSUE THREAD

**Issue by SPSeanLong** [appgate/terraform-provider-appgatesdp#160] opened 2021-09-17 21:01 UTC
Deploying an Appgate Appliance with the Portal role is possible without the use of any proxy certificate however when attempting the same process with the terraform provider it is required.
 
Using the `portal` hcl block without `proxy_12s` results in
`Error: Could not create appliance Validation error Validation failed. 
  portal.proxyP12s may not be empty if portal is enabled`

Then when `proxy_p12s{}` or `proxy_ps12{ content=""}` is present the tf plan will attempt to read a file at the blank 'content' path resulting in 
`   Error: unable to read p12 file content Error opening p12 file (): open : no such file or directory`

**Expected behavior**
Appliance role can be configured as Portal without providing any certificates for the same experience/config the UI allows

**Actual behavior**
Errors without a valid config for the proxy_p12s

**Comment by danijeel** [comment] 2021-09-20 07:40
Hi @SPSeanLong 
proxy_p12s is mandatory if portal is enabled.
>  Appliance role can be configured as Portal without providing any certificates for the same experience/config the UI allows

I cant reproduce this; when i tried with `5.4.1-25150-release`
![appliance_portal_web_gui_test](https://user-images.githubusercontent.com/1218385/133969579-c6bc0f39-2347-4456-9919-458d8a9fd816.png)

I get the same validation error in the UI as in terraform.

**Comment by danijeel** [comment] 2021-09-21 08:28
Closing this as its a none issue.

**Closed by danijeel** 2021-09-21 08:28 UTC
